PRAGMA encoding = 'UTF-8';

CREATE TABLE espacos (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    codigo TEXT,
    nome TEXT NOT NULL,
    tipo TEXT NOT NULL CHECK (tipo IN (
        'Sala', 'Laboratório', 'Auditório', 'Anfiteatro', 'Administrativo',
        'Biblioteca', 'Projeto', 'Espaço de estudo', 'Espaço de convivência',
        'Serviço', 'Outro'
    )),
    bloco TEXT,
    andar INTEGER,
    observacao TEXT
);

CREATE INDEX idx_espacos_codigo ON espacos(codigo);
CREATE INDEX idx_espacos_nome ON espacos(nome);
CREATE INDEX idx_espacos_tipo ON espacos(tipo);
CREATE INDEX idx_espacos_bloco ON espacos(bloco);
CREATE INDEX idx_espacos_andar ON espacos(andar);

CREATE VIEW salas AS
SELECT * FROM espacos WHERE tipo = 'Sala';

CREATE VIEW laboratorios AS
SELECT * FROM espacos WHERE tipo = 'Laboratório';

CREATE VIEW auditorios AS
SELECT * FROM espacos WHERE tipo IN ('Auditório', 'Anfiteatro');

CREATE VIEW por_bloco AS
SELECT bloco, id, codigo, nome, tipo, andar, observacao
FROM espacos
ORDER BY bloco, codigo, nome;

INSERT INTO espacos (codigo, nome, tipo, bloco, andar, observacao) VALUES
('A001', 'A001', 'Sala', 'A', NULL, NULL),
('A002', 'A002', 'Sala', 'A', NULL, NULL),
('A003', 'A003', 'Sala', 'A', NULL, NULL),
('A004', 'A004', 'Sala', 'A', NULL, NULL),
('A005', 'A005', 'Sala', 'A', NULL, NULL),
('A007', 'A007', 'Sala', 'A', NULL, NULL),
('A009', 'A009', 'Sala', 'A', NULL, NULL),
('A010', 'A010', 'Sala', 'A', NULL, NULL),
('A011', 'A011', 'Sala', 'A', NULL, NULL),
('A012', 'A012', 'Sala', 'A', NULL, NULL),
('A013', 'A013', 'Sala', 'A', NULL, NULL),
('A014', 'A014', 'Sala', 'A', NULL, NULL),
('A015', 'A015', 'Sala', 'A', NULL, NULL),
('A101', 'A101', 'Sala', 'A', 1, NULL),
('A127', 'A127', 'Sala', 'A', 1, NULL),
('B001', 'B001', 'Sala', 'B', NULL, NULL),
('B002/B004', 'B002/B004', 'Sala', 'B', NULL, NULL),
('B003', 'B003', 'Sala', 'B', NULL, NULL),
('B005', 'B005', 'Sala', 'B', NULL, NULL),
('B006', 'B006', 'Sala', 'B', NULL, NULL),
('B007', 'B007', 'Sala', 'B', NULL, NULL),
('B008', 'B008', 'Sala', 'B', NULL, NULL),
('B009', 'B009', 'Sala', 'B', NULL, NULL),
('B011', 'B011', 'Sala', 'B', NULL, NULL),
('B012', 'B012', 'Sala', 'B', NULL, NULL),
('B013', 'B013', 'Sala', 'B', NULL, NULL),
('B015', 'B015', 'Sala', 'B', NULL, NULL),
('B018/B020', 'B018/B020', 'Sala', 'B', NULL, NULL),
('B021', 'B021', 'Sala', 'B', NULL, NULL),
('B022', 'B022', 'Sala', 'B', NULL, NULL),
('B023', 'B023', 'Sala', 'B', NULL, NULL),
('B024', 'B024', 'Sala', 'B', NULL, NULL),
('B025', 'B025', 'Sala', 'B', NULL, NULL),
('C002', 'C002', 'Sala', 'C', NULL, NULL),
('C004', 'C004', 'Sala', 'C', NULL, NULL),
('C006', 'C006', 'Sala', 'C', NULL, NULL),
('C007', 'C007', 'Sala', 'C', NULL, NULL),
('C008', 'C008', 'Sala', 'C', NULL, NULL),
('C009', 'C009', 'Sala', 'C', NULL, NULL),
('C010', 'C010', 'Sala', 'C', NULL, NULL),
('C011', 'C011', 'Sala', 'C', NULL, NULL),
('C012', 'C012', 'Sala', 'C', NULL, NULL),
('C013/015', 'C013/015', 'Sala', 'C', NULL, NULL),
('C014', 'C014', 'Sala', 'C', NULL, NULL),
('C015', 'C015', 'Sala', 'C', NULL, NULL),
('C017', 'C017', 'Sala', 'C', NULL, NULL),
('C019', 'C019', 'Sala', 'C', NULL, NULL),
('C021', 'C021', 'Sala', 'C', NULL, NULL),
('D002', 'D002', 'Sala', 'D', 0, NULL),
('D003', 'D003', 'Sala', 'D', 0, NULL),
('D004', 'D004', 'Sala', 'D', 0, NULL),
('D005', 'D005', 'Sala', 'D', 0, NULL),
('D217', 'D217', 'Sala', 'D', 2, NULL),
('E101', 'E101', 'Sala', 'E', 1, NULL),
('E103', 'E103', 'Sala', 'E', 1, NULL),
('E104', 'E104', 'Sala', 'E', 1, NULL),
('E201', 'E201', 'Sala', 'E', 2, NULL),
('E205', 'E205', 'Sala', 'E', 2, NULL),
('E401/E402', 'E401/E402', 'Sala', 'E', 4, NULL),
('E403/E404', 'E403/E404', 'Sala', 'E', 4, NULL),
('E411', 'E411', 'Sala', 'E', 4, NULL),
('E423', 'E423', 'Sala', 'E', 4, NULL),
('E432', 'E432', 'Sala', 'E', 4, NULL),
('E433', 'E433', 'Sala', 'E', 4, NULL),
(NULL, 'Grad1', 'Laboratório', NULL, NULL, NULL),
(NULL, 'Grad2', 'Laboratório', NULL, NULL, NULL),
('C013/015', 'Grad3 C013/015', 'Laboratório', 'C', NULL, NULL),
(NULL, 'Grad4', 'Laboratório', NULL, NULL, NULL),
(NULL, 'Grad5', 'Laboratório', NULL, NULL, NULL),
(NULL, 'Laboratório de hardware', 'Laboratório', NULL, NULL, NULL),
(NULL, 'Laboratório de pós-graduação', 'Laboratório', NULL, NULL, NULL),
(NULL, 'Laboratórios de pesquisa', 'Laboratório', NULL, NULL, NULL),
(NULL, 'Laboratório de Inteligência Artíficial 1', 'Laboratório', NULL, NULL, NULL),
(NULL, 'Laboratório de Inteligência Artíficial 2', 'Laboratório', NULL, NULL, NULL),
(NULL, 'Anfiteatro', 'Anfiteatro', NULL, NULL, NULL),
(NULL, 'Auditório (Samsung)', 'Auditório', NULL, NULL, NULL),
(NULL, 'Auditório (Academy)', 'Auditório', NULL, NULL, NULL),
(NULL, 'Portaria', 'Serviço', NULL, NULL, NULL),
(NULL, 'Helpdesk', 'Serviço', NULL, NULL, NULL),
(NULL, 'RobôCIn', 'Projeto', NULL, NULL, NULL),
(NULL, 'LIVE', 'Projeto', NULL, NULL, NULL),
(NULL, 'Oficina', 'Outro', NULL, NULL, NULL),
(NULL, 'Sala de convivência', 'Espaço de convivência', NULL, NULL, NULL),
(NULL, 'Sala de Aposentados/Visitantes', 'Administrativo', NULL, NULL, NULL),
(NULL, 'Sala de Amamentação/Fraldário', 'Serviço', NULL, NULL, NULL),
(NULL, 'Gerinfra', 'Administrativo', NULL, NULL, NULL),
(NULL, 'Voltz', 'Projeto', NULL, NULL, NULL),
(NULL, 'ESTUFA', 'Projeto', NULL, NULL, NULL),
(NULL, 'Central telefônica', 'Serviço', NULL, NULL, NULL),
(NULL, 'Espaço alimentação', 'Serviço', NULL, NULL, NULL),
(NULL, 'Pátio externo', 'Espaço de convivência', NULL, NULL, NULL),
(NULL, 'Pátio coberto', 'Espaço de convivência', NULL, NULL, NULL),
(NULL, 'Diretório acadêmico', 'Administrativo', NULL, NULL, NULL),
(NULL, 'Biblioteca', 'Biblioteca', NULL, NULL, NULL),
(NULL, 'Biblioteca Setorial do CCEN', 'Biblioteca', NULL, NULL, NULL),
(NULL, 'Hall do CCEN', 'Outro', NULL, NULL, NULL),
(NULL, 'Secretaria de graduação', 'Administrativo', NULL, NULL, NULL),
(NULL, 'Secretaria de pós-graduação', 'Administrativo', NULL, NULL, NULL),
(NULL, 'Secretaria Geral', 'Administrativo', NULL, NULL, NULL),
(NULL, 'Assessoria de Comunicação', 'Administrativo', NULL, NULL, NULL),
(NULL, 'Financeiro', 'Administrativo', NULL, NULL, NULL),
(NULL, 'NEAP', 'Administrativo', NULL, NULL, NULL),
(NULL, 'NEAP - APOIO', 'Administrativo', NULL, NULL, NULL),
(NULL, 'SandPit', 'Projeto', NULL, NULL, NULL),
(NULL, 'Espaço Maker', 'Projeto', NULL, NULL, NULL),
(NULL, 'Pitch', 'Projeto', NULL, NULL, NULL),
(NULL, 'PET', 'Projeto', NULL, NULL, NULL),
(NULL, 'CITi', 'Projeto', NULL, NULL, NULL),
(NULL, 'Salas de reunião', 'Administrativo', NULL, NULL, NULL),
(NULL, 'Espaços de Projetos', 'Projeto', NULL, NULL, NULL),
(NULL, 'Projeto CIn-Motorola', 'Projeto', NULL, NULL, NULL),
(NULL, 'Projeto Softex', 'Projeto', NULL, NULL, NULL),
(NULL, 'Projeto VTEX', 'Projeto', NULL, NULL, NULL),
(NULL, 'CINCODERS', 'Projeto', NULL, NULL, NULL),
(NULL, 'MARATONA', 'Projeto', NULL, NULL, NULL),
(NULL, 'ESTUDIO', 'Projeto', NULL, NULL, NULL),
(NULL, 'INES', 'Projeto', NULL, NULL, NULL),
(NULL, 'PRO.NET', 'Projeto', NULL, NULL, NULL),
(NULL, 'PRIMO A ID', 'Projeto', NULL, NULL, NULL),
(NULL, 'Espaço reservado para o corpo administrativo', 'Administrativo', NULL, NULL, NULL),
(NULL, 'Ascom', 'Administrativo', NULL, NULL, NULL),
(NULL, 'Voxar Labs', 'Projeto', NULL, NULL, NULL),
(NULL, 'Espaço alimentação', 'Serviço', NULL, NULL, NULL),
(NULL, 'Espaço de convivência e estudo', 'Espaço de convivência', NULL, NULL, NULL),
(NULL, 'Copa e cozinha', 'Serviço', NULL, NULL, NULL),
(NULL, 'Depósito', 'Serviço', NULL, NULL, NULL);
